// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxncxIKxnt7VEKb76ezJS2ho-UG3ujloo',
    appId: '1:116645713117:web:cf7d041b1d20141fd47734',
    messagingSenderId: '116645713117',
    projectId: 'chatmeesagetest',
    authDomain: 'chatmeesagetest.firebaseapp.com',
    storageBucket: 'chatmeesagetest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqeoHxpiWhbEKAM0ETlo2gjq_KZU70a44',
    appId: '1:116645713117:android:33948461b321b331d47734',
    messagingSenderId: '116645713117',
    projectId: 'chatmeesagetest',
    storageBucket: 'chatmeesagetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeoDwzbFS9ZS6784gRvSOxTBpyuSqdGXY',
    appId: '1:116645713117:ios:ef8562d2b8de205dd47734',
    messagingSenderId: '116645713117',
    projectId: 'chatmeesagetest',
    storageBucket: 'chatmeesagetest.appspot.com',
    iosBundleId: 'com.example.chatMeesageDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeoDwzbFS9ZS6784gRvSOxTBpyuSqdGXY',
    appId: '1:116645713117:ios:29af28938b80c89dd47734',
    messagingSenderId: '116645713117',
    projectId: 'chatmeesagetest',
    storageBucket: 'chatmeesagetest.appspot.com',
    iosBundleId: 'com.example.chatMeesageDemo.RunnerTests',
  );
}
